# Generated by Django 3.2.7 on 2021-09-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름 없는 보드', max_length=50, verbose_name='보드 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자/시각')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='수정 일자/시각')),
            ],
            options={
                'verbose_name': 'TodoBoard',
                'verbose_name_plural': 'TodoBoards',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자/시각')),
                ('content', models.TextField(verbose_name='내용')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.todoboard', verbose_name='대상 보드')),
            ],
        ),
    ]
